# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1441, 777)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_2.setGeometry(QtCore.QRect(70, 160, 101, 41))
        self.bt_2.setObjectName("bt_2")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 30, 181, 41))
        self.label_1.setObjectName("label_1")
        self.bt_1 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_1.setGeometry(QtCore.QRect(70, 80, 121, 31))
        self.bt_1.setObjectName("bt_1")
        self.bt_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_6.setGeometry(QtCore.QRect(1290, 370, 101, 41))
        self.bt_6.setObjectName("bt_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 261, 41))
        self.label_2.setObjectName("label_2")
        self.bt_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_5.setGeometry(QtCore.QRect(1140, 370, 101, 41))
        self.bt_5.setObjectName("bt_5")
        self.bt_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_4.setGeometry(QtCore.QRect(70, 220, 101, 41))
        self.bt_4.setObjectName("bt_4")
        self.video = QtWidgets.QLabel(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(360, 20, 641, 451))
        self.video.setMinimumSize(QtCore.QSize(128, 72))
        self.video.setMaximumSize(QtCore.QSize(1280, 720))
        self.video.setObjectName("video")
        self.bt_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_3.setGeometry(QtCore.QRect(210, 220, 101, 41))
        self.bt_3.setObjectName("bt_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 270, 141, 41))
        self.label_3.setObjectName("label_3")
        self.bt_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_7.setGeometry(QtCore.QRect(210, 310, 91, 41))
        self.bt_7.setObjectName("bt_7")
        self.inf_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.inf_1.setGeometry(QtCore.QRect(1140, 440, 251, 31))
        self.inf_1.setObjectName("inf_1")
        self.inf_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.inf_2.setGeometry(QtCore.QRect(1140, 510, 251, 31))
        self.inf_2.setObjectName("inf_2")
        self.inf_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.inf_3.setGeometry(QtCore.QRect(70, 560, 941, 141))
        self.inf_3.setObjectName("inf_3")
        self.bt_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_8.setGeometry(QtCore.QRect(210, 80, 121, 31))
        self.bt_8.setObjectName("bt_8")
        self.video_2 = QtWidgets.QLabel(self.centralwidget)
        self.video_2.setGeometry(QtCore.QRect(1130, 90, 251, 211))
        self.video_2.setMinimumSize(QtCore.QSize(128, 72))
        self.video_2.setMaximumSize(QtCore.QSize(1280, 720))
        self.video_2.setObjectName("video_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1090, 440, 71, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1090, 510, 71, 41))
        self.label_5.setObjectName("label_5")
        self.bt_9 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_9.setGeometry(QtCore.QRect(70, 310, 131, 41))
        self.bt_9.setObjectName("bt_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1441, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_2.setText(_translate("MainWindow", "检测交通标志"))
        self.label_1.setText(_translate("MainWindow", "第一步：选择文件"))
        self.bt_1.setText(_translate("MainWindow", "选择文件/文件夹"))
        self.bt_6.setText(_translate("MainWindow", "下一张"))
        self.label_2.setText(_translate("MainWindow", "第二步：选择操作项"))
        self.bt_5.setText(_translate("MainWindow", "上一张"))
        self.bt_4.setText(_translate("MainWindow", "上一张图片"))
        self.video.setText(_translate("MainWindow", "                                      图片"))
        self.bt_3.setText(_translate("MainWindow", "下一张图片"))
        self.label_3.setText(_translate("MainWindow", "其他操作"))
        self.bt_7.setText(_translate("MainWindow", "退出程序"))
        self.inf_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.inf_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.inf_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">运行提示：</p></body></html>"))
        self.bt_8.setText(_translate("MainWindow", "选择视频"))
        self.video_2.setText(_translate("MainWindow", "           识别到的图片"))
        self.label_4.setText(_translate("MainWindow", "类 别："))
        self.label_5.setText(_translate("MainWindow", "含 义："))
        self.bt_9.setText(_translate("MainWindow", "神经网络检测识别"))
